### ISSUE TITLE
Ubuntu 18.04 安装后命令行使用报错

### ISSUE THREAD

**Issue by fengzhongsu** [yuhldr/ldr-translate#1]
终端启动报错
1.2.0
启动
Traceback (most recent call last):
  File "./ldr-translate.py", line 123, in _active_auto_translate
    self._active_translate_windows()
  File "./ldr-translate.py", line 145, in _active_translate_windows
    self.translate_win = Translate()
  File "/opt/ldr-translate/ui_translate.py", line 26, in __init__
    ui.add_from_file('./ui/translate.ui')
GLib.Error: gtk-builder-error-quark: ./ui/translate.ui:5:1 Required gtk+ version 3.24, current version is 3.22 (7)
而且桌面右上角图标不能退出

**Comment by yuhldr** [comment]
[v1.2.1](https://github.com/yuhldr/ldr-translate/releases/tag/v1.2.1)，已适配ubuntu18.04（虚拟机测试通过）

**Comment by ahuxjz** [comment]
Traceback (most recent call last):
  File "./ldr-translate.py", line 11, in <module>
    import gi
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)

**Comment by fengzhongsu** [comment]
您好，我已受到您的来信

**Comment by yuhldr** [comment]
> Traceback (most recent call last): File "./ldr-translate.py", line 11, in import gi File "/usr/lib/python3/dist-packages/gi/**init**.py", line 42, in from . import _gi ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/**init**.py)

使用最新版试试
